name: update-repo-docs

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'
  push:
    branches:
      - main
      
jobs:
  update-repo-docs:
    uses: ./.github/workflows/update-repo-docs.yml