name: update-repo-docs

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'
  push:
    branches:
      - main
      
jobs:
  update-repo-docs:
    permissions:
      contents: write
      pull-requests: write
    uses: fortify/shared-github/.github/workflows/reusable-update-repo-docs.yml@6b5f260306c9b9d6aadd2a606801c6ffe77cdb14